In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
def ler_csv(file, separador, encode, zebrado=False):
    return pd.read_csv(file, sep=separador, encoding=encode, squeeze = zebrado)

In [3]:
df_all_base = ler_csv("./Base/Base_Completa.csv", ';', 'utf-8', True)

C:\Users\Kimbelly\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3214: DtypeWarning: Columns (157) have mixed types. Specify dtype option on import or set low_memory=False.
  if (yield from self.run_code(code, result)):


In [4]:
dataset=df_all_base

In [5]:
#na vdd é classe 
#dividir dados em atributos e rótulos
#X = dataset.drop('CO_ENTIDADE', axis=1)
X = dataset[[ 'IN_LABORATORIO_INFORMATICA','IN_BIBLIOTECA', 'IN_AGUA_FILTRADA', 'IN_ENERGIA_REDE_PUBLICA','IN_AGUA_INEXISTENTE','IN_ESGOTO_INEXISTENTE','IN_QUADRA_ESPORTES', 'IN_SALA_LEITURA','IN_BIBLIOTECA_SALA_LEITURA', 'IN_INTERNET']]

dataset['rotulo'] = list(map(lambda x : 1 if x>300 else 0, dataset.loc[:,'MEDIA_TOTAL_5EF']))
y = dataset['rotulo']

In [6]:
# train_test_split método, que usaremos para dividir os dados aleatoriamente em conjuntos de treinamento e teste. 
#o test_size parâmetro especifica a proporção do conjunto de testes, que usamos 
#para dividir 20% dos dados no conjunto de testes e 80% para o treinamento.
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20) 

In [7]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

C:\Users\Kimbelly\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [8]:
y_pred = svclassifier.predict(X_test)

In [9]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[14714     0]
 [   21     0]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     14714
           1       0.00      0.00      0.00        21

   micro avg       1.00      1.00      1.00     14735
   macro avg       0.50      0.50      0.50     14735
weighted avg       1.00      1.00      1.00     14735



C:\Users\Kimbelly\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [10]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='rbf')
svclassifier.fit(X_train, y_train)

C:\Users\Kimbelly\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [11]:
y_pred = svclassifier.predict(X_test)

In [12]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[14714     0]
 [   21     0]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     14714
           1       0.00      0.00      0.00        21

   micro avg       1.00      1.00      1.00     14735
   macro avg       0.50      0.50      0.50     14735
weighted avg       1.00      1.00      1.00     14735



C:\Users\Kimbelly\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [13]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(X_train, y_train)

C:\Users\Kimbelly\Anaconda3\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [14]:
y_pred = svclassifier.predict(X_test)

In [15]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[14714     0]
 [   21     0]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     14714
           1       0.00      0.00      0.00        21

   micro avg       1.00      1.00      1.00     14735
   macro avg       0.50      0.50      0.50     14735
weighted avg       1.00      1.00      1.00     14735



C:\Users\Kimbelly\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [16]:
df=pd.DataFrame({'Actual':y_test, 'Predicted':y_pred})
df

Actual  Predicted
153         0          0
40313       0          0
50932       0          0
3730        0          0
16729       0          0
16889       0          0
25863       0          0
50269       0          0
9316        0          0
38864       0          0
67421       0          0
38224       0          0
68465       0          0
36892       0          0
35442       0          0
56248       0          0
17802       0          0
33204       0          0
59971       0          0
7332        0          0
31360       0          0
67950       0          0
28554       0          0
58110       0          0
34885       0          0
22095       0          0
24213       0          0
1685        0          0
66600       0          0
54064       0          0
...       ...        ...
61840       0          0
53723       0          0
14902       0          0
50099       0          0
33187       0          0
55296       0          0
5421        0          0
61487       0          0
55391       0          0
10532       0          0
27870       0          0
24897       0          0
49804       0          0
73285       0          0
36078       0          0
41589       0          0
73037       0          0
60554       0          0
13883       0          0
958         0          0
21593       0          0
14679       0          0
16505       0          0
27465       0          0
39342       0          0
27121       0          0
5351        0          0
18064       0          0
3209        0          0
61234       0          0

[14735 rows x 2 columns]